const fs = require('fs');
let code = fs.readFileSync('src/pages/workspace/ExecutiveReports.tsx', 'utf8');

const mdReplacement = `    });
    textContent += \`\\n---\\n*Generated by Vivexa*\\n\`;

    const blob = new Blob([textContent], { type: "text/markdown;charset=utf-8" });`;

code = code.replace(/    \}\);\n\n    const blob = new Blob\(\[textContent\], \{ type: "text\/markdown;charset=utf-8" \}\);/, mdReplacement);

fs.writeFileSync('src/pages/workspace/ExecutiveReports.tsx', code);
