import React from 'react';
import { 
  Download, FileSpreadsheet, FileCode, Code2, FileText, 
  BookOpen, Layers, CheckCircle2, X
} from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import { DatasetProfile } from '@/lib/dataEngine';

interface Props {
  rows: Record<string, any>[];
  columns: string[];
  datasetName?: string;
  profile?: DatasetProfile | null;
  onClose?: () => void;
}

export default function ExportPackModal({ rows, columns, datasetName = "Dataset", profile, onClose }: Props) {
  
  const handleExportCSV = () => {
    const ws = XLSX.utils.json_to_sheet(rows);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "CleanedDataset");
    XLSX.writeFile(wb, `${datasetName}_cleaned.csv`);
    toast.success("CSV dataset exported successfully");
  };

  const handleExportExcel = () => {
    const ws = XLSX.utils.json_to_sheet(rows);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "Data");
    if (profile) {
      const summarySheet = XLSX.utils.json_to_sheet(profile.columns.map(c => ({
        Column: c.name,
        Type: c.type,
        Nulls: c.nullCount,
        NullPct: `${c.nullPercentage}%`,
        Uniques: c.uniqueCount
      })));
      XLSX.utils.book_append_sheet(wb, summarySheet, "DataDictionary");
    }
    XLSX.writeFile(wb, `${datasetName}_workbook.xlsx`);
    toast.success("Excel Workbook exported successfully");
  };

  const handleExportPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(18);
    doc.text(`Enterprise Data Audit & Cleaning Report`, 14, 20);
    doc.setFontSize(12);
    doc.text(`Dataset Name: ${datasetName}`, 14, 30);
    doc.text(`Total Rows: ${rows.length}`, 14, 38);
    doc.text(`Total Columns: ${columns.length}`, 14, 46);

    if (profile) {
      doc.text(`Data Quality Score: ${profile.scores.dataQualityScore}/100`, 14, 56);
      doc.text(`Completeness Score: ${profile.scores.completenessScore}/100`, 14, 64);
      doc.text(`Consistency Score: ${profile.scores.consistencyScore}/100`, 14, 72);
      doc.text(`ML Readiness Score: ${profile.scores.mlReadinessScore}/100`, 14, 80);
      doc.text(`Risk Level: ${profile.scores.riskLevel}`, 14, 88);
    }

    doc.setFontSize(10);
    doc.text(`Generated by Vivexa Enterprise AI Data Analyst`, 14, 110);
    doc.save(`${datasetName}_audit_report.pdf`);
    toast.success("PDF Executive Report exported");
  };

  const handleExportPython = () => {
    const code = `# Enterprise Data Pipeline - ${datasetName}
import pandas as pd
import numpy as np

# Load raw dataset
df = pd.read_csv("${datasetName}.csv")

# 1. Missing Value Imputation
for col in df.select_dtypes(include=[np.number]).columns:
    df[col].fillna(df[col].median(), inplace=True)

for col in df.select_dtypes(include=['object']).columns:
    df[col].fillna(df[col].mode()[0] if not df[col].mode().empty else 'N/A', inplace=True)

# 2. Outlier Cap (IQR)
for col in df.select_dtypes(include=[np.number]).columns:
    q25 = df[col].quantile(0.25)
    q75 = df[col].quantile(0.75)
    iqr = q75 - q25
    lower = q25 - 1.5 * iqr
    upper = q75 + 1.5 * iqr
    df[col] = np.clip(df[col], lower, upper)

# Save cleaned output
df.to_csv("${datasetName}_cleaned.csv", index=False)
print("Pipeline execution complete.")
`;
    const blob = new Blob([code], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `pipeline_${datasetName.toLowerCase().replace(/\s+/g, '_')}.py`;
    a.click();
    toast.success("Python Pipeline Script exported");
  };

  const handleExportSQL = () => {
    const sql = `-- Data Cleaning & Standardization SQL Queries for ${datasetName}
-- 1. Create Cleaned Staging Table
CREATE TABLE cleaned_${datasetName.toLowerCase().replace(/[^a-z0-9]/g, '_')} AS
SELECT
${columns.map(c => `  COALESCE(${c}, 'N/A') AS ${c.toLowerCase().replace(/\s+/g, '_')}`).join(',\n')}
FROM raw_${datasetName.toLowerCase().replace(/[^a-z0-9]/g, '_')};

-- 2. Remove Duplicates
WITH Deduplicated AS (
  SELECT *, ROW_NUMBER() OVER (PARTITION BY ${columns.slice(0, 3).join(', ')}) AS rn
  FROM cleaned_${datasetName.toLowerCase().replace(/[^a-z0-9]/g, '_')}
)
DELETE FROM Deduplicated WHERE rn > 1;
`;
    const blob = new Blob([sql], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `cleaning_${datasetName.toLowerCase().replace(/\s+/g, '_')}.sql`;
    a.click();
    toast.success("SQL Queries exported");
  };

  const handleExportJupyterNotebook = () => {
    const ipynb = {
      cells: [
        {
          cell_type: "markdown",
          metadata: {},
          source: [`# ${datasetName} - Automated EDA & Data Cleaning Notebook\n`, `Generated by Vivexa Enterprise AI Data Analyst.`]
        },
        {
          cell_type: "code",
          execution_count: null,
          metadata: {},
          outputs: [],
          source: [
            "import pandas as pd\n",
            "import numpy as np\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n\n",
            `df = pd.read_csv("${datasetName}.csv")\n`,
            "df.info()\n",
            "df.describe()"
          ]
        }
      ],
      metadata: { language_info: { name: "python" } },
      nbformat: 4,
      nbformat_minor: 2
    };
    const blob = new Blob([JSON.stringify(ipynb, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `eda_${datasetName.toLowerCase().replace(/\s+/g, '_')}.ipynb`;
    a.click();
    toast.success("Jupyter Notebook (.ipynb) exported");
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/70 backdrop-blur-md">
      <Card className="w-full max-w-2xl bg-slate-900 border-slate-800 shadow-2xl relative">
        <CardHeader className="flex flex-row items-center justify-between border-b border-slate-800">
          <div>
            <CardTitle className="text-xl font-bold text-white flex items-center gap-2">
              <Download className="h-5 w-5 text-indigo-400" /> Enterprise Export Pack Generator
            </CardTitle>
            <CardDescription className="text-slate-400 text-xs mt-1">
              Export datasets, reports, pipeline scripts, and SQL queries.
            </CardDescription>
          </div>
          {onClose && (
            <button onClick={onClose} className="text-slate-400 hover:text-white p-1">
              <X className="h-5 w-5" />
            </button>
          )}
        </CardHeader>
        <CardContent className="p-6 grid grid-cols-1 sm:grid-cols-2 gap-4">
          <Button onClick={handleExportCSV} variant="outline" className="h-16 justify-start border-slate-800 hover:bg-slate-800 text-left bg-slate-950/50">
            <FileSpreadsheet className="h-6 w-6 text-emerald-400 mr-3 shrink-0" />
            <div>
              <div className="font-bold text-white text-sm">Cleaned Dataset (CSV)</div>
              <div className="text-[10px] text-slate-400">Standard CSV format for data tools</div>
            </div>
          </Button>

          <Button onClick={handleExportExcel} variant="outline" className="h-16 justify-start border-slate-800 hover:bg-slate-800 text-left bg-slate-950/50">
            <BookOpen className="h-6 w-6 text-indigo-400 mr-3 shrink-0" />
            <div>
              <div className="font-bold text-white text-sm">Excel Workbook (.xlsx)</div>
              <div className="text-[10px] text-slate-400">Includes Data & Data Dictionary</div>
            </div>
          </Button>

          <Button onClick={handleExportPDF} variant="outline" className="h-16 justify-start border-slate-800 hover:bg-slate-800 text-left bg-slate-950/50">
            <FileText className="h-6 w-6 text-rose-400 mr-3 shrink-0" />
            <div>
              <div className="font-bold text-white text-sm">Executive Audit Report (PDF)</div>
              <div className="text-[10px] text-slate-400">Data quality scores & risk summary</div>
            </div>
          </Button>

          <Button onClick={handleExportPython} variant="outline" className="h-16 justify-start border-slate-800 hover:bg-slate-800 text-left bg-slate-950/50">
            <Code2 className="h-6 w-6 text-amber-400 mr-3 shrink-0" />
            <div>
              <div className="font-bold text-white text-sm">Python Pipeline Script (.py)</div>
              <div className="text-[10px] text-slate-400">Pandas cleaning pipeline code</div>
            </div>
          </Button>

          <Button onClick={handleExportSQL} variant="outline" className="h-16 justify-start border-slate-800 hover:bg-slate-800 text-left bg-slate-950/50">
            <FileCode className="h-6 w-6 text-sky-400 mr-3 shrink-0" />
            <div>
              <div className="font-bold text-white text-sm">SQL Queries (.sql)</div>
              <div className="text-[10px] text-slate-400">Database staging & cleaning queries</div>
            </div>
          </Button>

          <Button onClick={handleExportJupyterNotebook} variant="outline" className="h-16 justify-start border-slate-800 hover:bg-slate-800 text-left bg-slate-950/50">
            <Layers className="h-6 w-6 text-purple-400 mr-3 shrink-0" />
            <div>
              <div className="font-bold text-white text-sm">Jupyter Notebook (.ipynb)</div>
              <div className="text-[10px] text-slate-400">Interactive EDA & data preparation</div>
            </div>
          </Button>
        </CardContent>
      </Card>
    </div>
  );
}
