/**
 * SemanticMetricDictionaryService.ts
 * 
 * Enterprise Semantic Metric Dictionary & Pre-Calculated Entity Store
 * Maintains a centralized semantic dictionary of enterprise business metrics
 * (ARR, MRR, LTV, CAC, Churn, EBITDA, NRR, Rule of 40, Gross Margin, ARPU + Custom Metrics).
 * Injects verified exact Python & SQL formulas into LLM system prompts to eliminate logic hallucinations.
 */

export interface SemanticMetricDefinition {
  metricId: string;
  name: string;
  aliases: string[];
  category: "Revenue" | "SaaS" | "Financial" | "Customer" | "Efficiency" | "User Growth" | "Operational" | "Risk" | "Custom";
  pythonFormula: string;
  sqlFormula: string;
  description: string;
  requiredColumns: string[];
  owner?: string;
  status?: "Verified" | "Draft";
  expression?: string;
  lineage?: string[];
}

export class SemanticMetricDictionaryService {
  private static metricsDictionary: Record<string, SemanticMetricDefinition> = {
    ARR: {
      metricId: "ARR",
      name: "Annual Recurring Revenue",
      aliases: ["arr", "annual recurring revenue", "annual revenue", "yearly recurring revenue"],
      category: "Revenue",
      pythonFormula: "df['arr'] = df['mrr'] * 12 if 'mrr' in df.columns else df.groupby('customer_id')['recurring_amount'].sum() * 12",
      sqlFormula: "SUM(monthly_recurring_revenue) * 12",
      description: "Total normalized recurring revenue generated by active subscriptions on an annualized basis.",
      requiredColumns: ["mrr", "recurring_amount", "amount", "subscription_fee"],
      owner: "Finance Data Team",
      status: "Verified",
      lineage: ["Stripe.Invoices", "Salesforce.Contracts", "Lakehouse.Fact_Revenue"]
    },
    MRR: {
      metricId: "MRR",
      name: "Monthly Recurring Revenue",
      aliases: ["mrr", "monthly recurring revenue", "monthly revenue", "monthly_recurring_revenue"],
      category: "Revenue",
      pythonFormula: "df['mrr'] = df.groupby('customer_id')['recurring_amount'].sum()",
      sqlFormula: "SUM(monthly_subscription_amount) - SUM(discounts)",
      description: "Total predictable revenue generated by active subscriptions per month.",
      requiredColumns: ["mrr", "recurring_amount", "amount"],
      owner: "Finance Data Team",
      status: "Verified",
      lineage: ["Stripe.Invoices", "Salesforce.Contracts", "Lakehouse.Fact_Revenue"]
    },
    CAC: {
      metricId: "CAC",
      name: "Customer Acquisition Cost",
      aliases: ["cac", "customer acquisition cost", "acquisition cost"],
      category: "SaaS",
      pythonFormula: "cac = df['sales_marketing_spend'].sum() / max(1, df['new_customers_acquired'].sum())",
      sqlFormula: "SUM(sales_marketing_spend) / NULLIF(SUM(new_customers_acquired), 0)",
      description: "Total sales and marketing expenditure divided by the number of new customers acquired.",
      requiredColumns: ["sales_marketing_spend", "new_customers_acquired", "marketing_spend"],
      owner: "Marketing Analytics",
      status: "Draft",
      lineage: ["GoogleAds.Spend", "LinkedIn.Spend", "HubSpot.Deals"]
    },
    LTV: {
      metricId: "LTV",
      name: "Customer Lifetime Value",
      aliases: ["ltv", "lifetime value", "clv", "customer lifetime value"],
      category: "Customer",
      pythonFormula: "ltv = (df['arpu'].mean() * df['gross_margin_pct'].mean()) / max(0.001, df['churn_rate'].mean())",
      sqlFormula: "(AVG(arpu) * AVG(gross_margin_pct)) / NULLIF(AVG(churn_rate), 0)",
      description: "Estimated total gross margin dollar revenue a customer generates over their lifetime.",
      requiredColumns: ["arpu", "gross_margin_pct", "churn_rate"],
      owner: "Finance Data Team",
      status: "Verified",
      lineage: ["Lakehouse.Dim_Customer", "Stripe.Invoices"]
    },
    CHURN_RATE: {
      metricId: "CHURN_RATE",
      name: "Logo Churn Rate",
      aliases: ["churn", "churn rate", "logo churn", "customer churn"],
      category: "Risk",
      pythonFormula: "churn_rate = (df['churned_customers'].sum() / max(1, df['start_period_customers'].sum())) * 100",
      sqlFormula: "SELECT (COUNT(CASE WHEN churned_at > CURRENT_DATE - 30 THEN 1 END) / COUNT(CASE WHEN created_at < CURRENT_DATE - 30 THEN 1 END)) * 100 FROM customers",
      description: "Percentage of unique active customer accounts cancelled in the trailing 30 days.",
      requiredColumns: ["churned_customers", "start_period_customers", "status"],
      owner: "Customer Success",
      status: "Verified",
      lineage: ["Zendesk.Accounts", "Lakehouse.Dim_Customer"]
    },
    EBITDA: {
      metricId: "EBITDA",
      name: "EBITDA",
      aliases: ["ebitda", "earnings before interest tax depreciation amortization"],
      category: "Financial",
      pythonFormula: "ebitda = df['gross_profit'].sum() - df['opex'].sum()",
      sqlFormula: "SUM(gross_profit) - SUM(operating_expenses)",
      description: "Earnings Before Interest, Taxes, Depreciation, and Amortization.",
      requiredColumns: ["gross_profit", "opex", "operating_expenses", "revenue", "cogs"],
      owner: "Finance Data Team",
      status: "Verified",
      lineage: ["NetSuite.GL", "Lakehouse.Fact_Financials"]
    },
    NRR: {
      metricId: "NRR",
      name: "Net Retention Rate (NRR)",
      aliases: ["nrr", "net revenue retention", "net retention", "net_retention_rate"],
      category: "Revenue",
      pythonFormula: "nrr = ((df['starting_mrr'].sum() + df['expansion_mrr'].sum() - df['contraction_mrr'].sum() - df['churn_mrr'].sum()) / max(1, df['starting_mrr'].sum())) * 100",
      sqlFormula: "SELECT ((sum(start_mrr) + sum(expansion) - sum(downgrade) - sum(churn)) / sum(start_mrr)) * 100 FROM mrr_waterfall",
      description: "Revenue retained from existing customers including expansions, minus downgrades and churn.",
      requiredColumns: ["starting_mrr", "expansion_mrr", "contraction_mrr", "churn_mrr"],
      owner: "Finance Data Team",
      status: "Verified",
      lineage: ["Lakehouse.Fact_MRR_Waterfall"]
    },
    DAU: {
      metricId: "DAU",
      name: "Daily Active Users (DAU)",
      aliases: ["dau", "daily active users", "active users", "daily_active_users"],
      category: "User Growth",
      pythonFormula: "dau = df[df['action_type'].isin(['query', 'view', 'edit'])]['user_id'].nunique()",
      sqlFormula: "SELECT COUNT(DISTINCT user_id) FROM events_log WHERE timestamp >= CURRENT_DATE - 1",
      description: "Unique authenticated user sessions performing a core platform action.",
      requiredColumns: ["user_id", "timestamp", "action_type"],
      owner: "Product Data",
      status: "Verified",
      lineage: ["Mixpanel.Events", "Lakehouse.Fact_Session"]
    },
    RULE_OF_40: {
      metricId: "RULE_OF_40",
      name: "Rule of 40",
      aliases: ["rule of 40", "rule of forty", "r40"],
      category: "Efficiency",
      pythonFormula: "rule_of_40 = df['revenue_growth_rate_pct'].mean() + df['free_cash_flow_margin_pct'].mean()",
      sqlFormula: "AVG(revenue_growth_rate_pct) + AVG(free_cash_flow_margin_pct)",
      description: "SaaS efficiency benchmark principle: Growth Rate (%) + Free Cash Flow Margin (%) should exceed 40%.",
      requiredColumns: ["revenue_growth_rate_pct", "free_cash_flow_margin_pct", "ebitda_margin_pct"],
      owner: "RevOps",
      status: "Verified",
      lineage: ["Lakehouse.Fact_Financials"]
    }
  };

  /**
   * Register or update a custom semantic metric definition
   */
  public static addOrUpdateMetric(metric: SemanticMetricDefinition): SemanticMetricDefinition {
    const key = metric.metricId.toUpperCase().replace(/[^A-Z0-9_]/g, "_");
    const aliases = Array.from(new Set([
      ...(metric.aliases || []),
      key.toLowerCase(),
      metric.name.toLowerCase(),
      metric.metricId.toLowerCase()
    ]));

    const fullMetric: SemanticMetricDefinition = {
      ...metric,
      metricId: key,
      aliases,
      owner: metric.owner || "Enterprise Data Team",
      status: metric.status || "Verified",
      requiredColumns: metric.requiredColumns || [],
      lineage: metric.lineage || ["Lakehouse.Warehouse"]
    };

    this.metricsDictionary[key] = fullMetric;
    return fullMetric;
  }

  public static removeMetric(metricId: string): boolean {
    const key = metricId.toUpperCase().replace(/[^A-Z0-9_]/g, "_");
    if (this.metricsDictionary[key]) {
      delete this.metricsDictionary[key];
      return true;
    }
    return false;
  }

  public static getMetric(metricId: string): SemanticMetricDefinition | undefined {
    const key = metricId.toUpperCase().replace(/[^A-Z0-9_]/g, "_");
    return this.metricsDictionary[key];
  }

  /**
   * Identifies metrics referenced in a natural language query and returns formula guidance.
   */
  public static detectAndInjectMetricFormulas(query: string): string {
    const lowerQuery = query.toLowerCase();
    const matchedMetrics: SemanticMetricDefinition[] = [];

    Object.values(this.metricsDictionary).forEach((metric) => {
      const isMatched = metric.aliases.some((alias) => lowerQuery.includes(alias)) ||
                        lowerQuery.includes(metric.name.toLowerCase()) ||
                        lowerQuery.includes(metric.metricId.toLowerCase());
      if (isMatched && !matchedMetrics.some(m => m.metricId === metric.metricId)) {
        matchedMetrics.push(metric);
      }
    });

    if (matchedMetrics.length === 0) {
      return "";
    }

    let promptContext = "\n--- SEMANTIC METRIC DICTIONARY (ENTERPRISE FORMULAS) ---\n";
    matchedMetrics.forEach((m) => {
      promptContext += `Metric: ${m.name} (${m.metricId})\n`;
      promptContext += `Description: ${m.description}\n`;
      if (m.expression) promptContext += `Expression: ${m.expression}\n`;
      promptContext += `Exact Python Formula: ${m.pythonFormula}\n`;
      promptContext += `Exact SQL Formula: ${m.sqlFormula}\n\n`;
    });
    promptContext += "Use the exact formula logic specified above when computing these target metrics.\n";

    return promptContext;
  }

  public static getAllMetrics(): SemanticMetricDefinition[] {
    return Object.values(this.metricsDictionary);
  }
}
