/**
 * SemanticMetricDictionaryService.ts
 * 
 * Upgrade 12: Semantic Metric Dictionary & Pre-Calculated Entity Store
 * Maintains a centralized semantic dictionary of enterprise business metrics
 * (ARR, MRR, LTV, CAC, Churn, EBITDA, NRR, Rule of 40, Gross Margin, ARPU).
 * Injects verified exact Python & SQL formulas into LLM system prompts to eliminate logic hallucinations.
 */

export interface SemanticMetricDefinition {
  metricId: string;
  name: string;
  aliases: string[];
  category: "Revenue" | "SaaS" | "Financial" | "Customer" | "Efficiency";
  pythonFormula: string;
  sqlFormula: string;
  description: string;
  requiredColumns: string[];
}

export class SemanticMetricDictionaryService {
  private static metricsDictionary: Record<string, SemanticMetricDefinition> = {
    ARR: {
      metricId: "ARR",
      name: "Annual Recurring Revenue",
      aliases: ["arr", "annual recurring revenue", "annual revenue", "yearly recurring revenue"],
      category: "Revenue",
      pythonFormula: "df['arr'] = df['mrr'] * 12 if 'mrr' in df.columns else df.groupby('customer_id')['recurring_amount'].sum() * 12",
      sqlFormula: "SUM(monthly_recurring_revenue) * 12",
      description: "Total normalized recurring revenue generated by active subscriptions on an annualized basis.",
      requiredColumns: ["mrr", "recurring_amount", "amount", "subscription_fee"]
    },
    MRR: {
      metricId: "MRR",
      name: "Monthly Recurring Revenue",
      aliases: ["mrr", "monthly recurring revenue", "monthly revenue"],
      category: "Revenue",
      pythonFormula: "df['mrr'] = df.groupby('customer_id')['recurring_amount'].sum()",
      sqlFormula: "SUM(monthly_recurring_revenue)",
      description: "Total predictable revenue generated by active subscriptions per month.",
      requiredColumns: ["mrr", "recurring_amount", "amount"]
    },
    CAC: {
      metricId: "CAC",
      name: "Customer Acquisition Cost",
      aliases: ["cac", "customer acquisition cost", "acquisition cost"],
      category: "SaaS",
      pythonFormula: "cac = df['sales_marketing_spend'].sum() / max(1, df['new_customers_acquired'].sum())",
      sqlFormula: "SUM(sales_marketing_spend) / NULLIF(SUM(new_customers_acquired), 0)",
      description: "Total sales and marketing expenditure divided by the number of new customers acquired.",
      requiredColumns: ["sales_marketing_spend", "new_customers_acquired", "marketing_spend"]
    },
    LTV: {
      metricId: "LTV",
      name: "Customer Lifetime Value",
      aliases: ["ltv", "lifetime value", "clv", "customer lifetime value"],
      category: "Customer",
      pythonFormula: "ltv = (df['arpu'].mean() * df['gross_margin_pct'].mean()) / max(0.001, df['churn_rate'].mean())",
      sqlFormula: "(AVG(arpu) * AVG(gross_margin_pct)) / NULLIF(AVG(churn_rate), 0)",
      description: "Estimated total gross margin dollar revenue a customer generates over their lifetime.",
      requiredColumns: ["arpu", "gross_margin_pct", "churn_rate"]
    },
    CHURN_RATE: {
      metricId: "CHURN_RATE",
      name: "Customer Churn Rate",
      aliases: ["churn", "churn rate", "logo churn", "customer churn"],
      category: "SaaS",
      pythonFormula: "churn_rate = (df['churned_customers'].sum() / max(1, df['start_period_customers'].sum())) * 100",
      sqlFormula: "(SUM(churned_customers) * 100.0) / NULLIF(SUM(start_period_customers), 0)",
      description: "Percentage of customers who cancel or non-renew their subscription during a given period.",
      requiredColumns: ["churned_customers", "start_period_customers", "status"]
    },
    EBITDA: {
      metricId: "EBITDA",
      name: "EBITDA",
      aliases: ["ebitda", "earnings before interest tax depreciation amortization"],
      category: "Financial",
      pythonFormula: "ebitda = df['gross_profit'].sum() - df['opex'].sum()",
      sqlFormula: "SUM(gross_profit) - SUM(operating_expenses)",
      description: "Earnings Before Interest, Taxes, Depreciation, and Amortization.",
      requiredColumns: ["gross_profit", "opex", "operating_expenses", "revenue", "cogs"]
    },
    NRR: {
      metricId: "NRR",
      name: "Net Revenue Retention",
      aliases: ["nrr", "net revenue retention", "net retention"],
      category: "SaaS",
      pythonFormula: "nrr = ((df['starting_mrr'].sum() + df['expansion_mrr'].sum() - df['contraction_mrr'].sum() - df['churn_mrr'].sum()) / max(1, df['starting_mrr'].sum())) * 100",
      sqlFormula: "((SUM(starting_mrr) + SUM(expansion_mrr) - SUM(contraction_mrr) - SUM(churn_mrr)) * 100.0) / NULLIF(SUM(starting_mrr), 0)",
      description: "Percentage of recurring revenue retained from existing customers over a specified time period.",
      requiredColumns: ["starting_mrr", "expansion_mrr", "contraction_mrr", "churn_mrr"]
    },
    RULE_OF_40: {
      metricId: "RULE_OF_40",
      name: "Rule of 40",
      aliases: ["rule of 40", "rule of forty", "r40"],
      category: "Efficiency",
      pythonFormula: "rule_of_40 = df['revenue_growth_rate_pct'].mean() + df['free_cash_flow_margin_pct'].mean()",
      sqlFormula: "AVG(revenue_growth_rate_pct) + AVG(free_cash_flow_margin_pct)",
      description: "SaaS efficiency benchmark principle: Growth Rate (%) + Free Cash Flow Margin (%) should exceed 40%.",
      requiredColumns: ["revenue_growth_rate_pct", "free_cash_flow_margin_pct", "ebitda_margin_pct"]
    }
  };

  /**
   * Identifies metrics referenced in a natural language query and returns formula guidance.
   */
  public static detectAndInjectMetricFormulas(query: string): string {
    const lowerQuery = query.toLowerCase();
    const matchedMetrics: SemanticMetricDefinition[] = [];

    Object.values(this.metricsDictionary).forEach((metric) => {
      const isMatched = metric.aliases.some((alias) => lowerQuery.includes(alias));
      if (isMatched) {
        matchedMetrics.push(metric);
      }
    });

    if (matchedMetrics.length === 0) {
      return "";
    }

    let promptContext = "\n--- SEMANTIC METRIC DICTIONARY (ENTERPRISE FORMULAS) ---\n";
    matchedMetrics.forEach((m) => {
      promptContext += `Metric: ${m.name} (${m.metricId})\n`;
      promptContext += `Description: ${m.description}\n`;
      promptContext += `Exact Python Formula: ${m.pythonFormula}\n`;
      promptContext += `Exact SQL Formula: ${m.sqlFormula}\n\n`;
    });
    promptContext += "Use the exact formula logic specified above when computing these target metrics.\n";

    return promptContext;
  }

  public static getAllMetrics(): SemanticMetricDefinition[] {
    return Object.values(this.metricsDictionary);
  }
}
