import { PublicNavbar } from "@/components/landing/PublicNavbar";
import { PublicFooter } from "@/components/landing/PublicFooter";
import { AppBackground } from "@/components/layout/AppBackground";
import { SEOHead } from "@/components/seo/SEOHead";
import { Link } from "react-router-dom";
import { Building2, Globe, Shield, Target, ArrowRight, Award, CheckCircle2 } from "lucide-react";

export default function AboutPage() {
  return (
    <div className="relative min-h-screen bg-[#030712] text-white selection:bg-indigo-500/30">
      <SEOHead
        title="About Vivexa | The Enterprise AI Decision Operating System"
        description="Learn how Vivexa was founded by IIT Jodhpur AI researchers to eliminate corporate data bottlenecks through autonomous data science and causal intelligence."
        keywords={[
          "About Vivexa",
          "Vivexa Founders",
          "Paras Bishnoi",
          "Karunya Sharma",
          "IIT Jodhpur AI",
          "Enterprise AI Company",
          "Autonomous Data Science Platform"
        ]}
      />
      <AppBackground centered={false}>
        <PublicNavbar />

        <main className="pt-28 pb-20 relative z-10 max-w-7xl mx-auto px-6 lg:px-8 space-y-16">
          {/* Hero */}
          <div className="text-center max-w-3xl mx-auto space-y-4">
            <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-300 text-xs font-bold">
              <Building2 className="h-4 w-4" /> About Vivexa AI
            </div>
            <h1 className="text-4xl sm:text-6xl font-black tracking-tight">
              Empowering Leaders with <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 via-purple-400 to-cyan-400">Autonomous Intelligence</span>
            </h1>
            <p className="text-slate-400 text-sm sm:text-base leading-relaxed">
              Vivexa is built to transform complex, multi-source enterprise data into clear, trustworthy decisions in seconds—backed by rigorous statistical models and full auditability.
            </p>
          </div>

          {/* Stats Grid */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {[
              { label: "Queries Processed", val: "100M+" },
              { label: "Average Time Saved", val: "84%" },
              { label: "SOC2 & GDPR Compliant", val: "100%" },
              { label: "Enterprise Uptime SLA", val: "99.99%" }
            ].map((st, i) => (
              <div key={i} className="enterprise-card rounded-2xl p-6 text-center space-y-1">
                <div className="text-3xl font-black text-indigo-400 font-mono">{st.val}</div>
                <div className="text-xs text-slate-400 font-medium">{st.label}</div>
              </div>
            ))}
          </div>

          {/* Core Values */}
          <div className="space-y-8">
            <div className="text-center space-y-1">
              <h2 className="text-2xl font-bold text-white">Our Core Principles</h2>
              <p className="text-xs text-slate-400">Guiding every line of code, kernel execution, and prompt guardrail.</p>
            </div>

            <div className="grid md:grid-cols-3 gap-6">
              {[
                { title: "Zero Hallucination Tolerance", icon: Shield, desc: "Every insight generated by Vivexa is grounded in deterministic SQL, verifiable code, and audited dataset columns." },
                { title: "Transparent Causal Logic", icon: Target, desc: "We don't provide black-box predictions. You get inspectable Python code, SQL scripts, and statistical confidence bounds." },
                { title: "Enterprise-Grade Privacy", icon: Globe, desc: "Your sensitive data never leaves your VPC. We support air-gapped on-premise execution and zero-data-retention AI SLAs." }
              ].map((val, idx) => {
                const Icon = val.icon;
                return (
                  <div key={idx} className="enterprise-card rounded-2xl p-6 space-y-3">
                    <div className="p-2.5 bg-indigo-500/10 border border-indigo-500/20 rounded-xl text-indigo-400 w-fit">
                      <Icon className="h-5 w-5" />
                    </div>
                    <h3 className="text-lg font-bold text-white">{val.title}</h3>
                    <p className="text-xs text-slate-400 leading-relaxed">{val.desc}</p>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Founders Feature */}
          <div className="bg-gradient-to-r from-indigo-950/60 via-slate-900 to-purple-950/60 border border-indigo-500/30 rounded-3xl p-8 flex flex-col md:flex-row items-center justify-between gap-6">
            <div className="space-y-2 max-w-xl">
              <div className="text-xs font-bold text-indigo-400 uppercase tracking-wider">Meet the Visionaries</div>
              <h3 className="text-2xl font-bold text-white">Founded by IIT Jodhpur AI Researchers</h3>
              <p className="text-xs text-slate-300 leading-relaxed">
                Learn more about Paras (Founder & CEO) and Karunya Sharma (Co-Founder & CTO) and their mission to democratize enterprise decision science.
              </p>
            </div>
            <Link to="/founders" className="px-6 py-3 bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold rounded-xl shrink-0 transition-colors flex items-center gap-2">
              View Founders Page <ArrowRight className="h-3.5 w-3.5" />
            </Link>
          </div>
        </main>

        <PublicFooter />
      </AppBackground>
    </div>
  );
}
