import { useState } from "react";
import { useSearchParams, Link } from "react-router-dom";
import { PublicNavbar } from "@/components/landing/PublicNavbar";
import { PublicFooter } from "@/components/landing/PublicFooter";
import { AppBackground } from "@/components/layout/AppBackground";
import {
  FileText, Code2, HelpCircle, Activity, BookOpen, Terminal, CheckCircle2, Search, ArrowRight, ExternalLink
} from "lucide-react";

export default function ResourcesPage() {
  const [searchParams, setSearchParams] = useSearchParams();
  const activeTab = searchParams.get("tab") || "docs";
  const [query, setQuery] = useState("");

  const faqs = [
    { q: "How does Vivexa connect to my database?", a: "Vivexa connects via secure SSL/TLS read-only connection pooling. We support Snowflake, BigQuery, PostgreSQL, MySQL, Redshift, and SAP without requiring ETL pipeline configuration." },
    { q: "Does Vivexa store or train models on my private data?", a: "No. Vivexa adheres strictly to zero data retention and zero AI training SLAs. Your raw data remains inside your database or private cloud VPC." },
    { q: "What skills are required to use Vivexa?", a: "Vivexa is built for both business executives and technical data scientists. Non-technical users ask questions in natural language, while technical users inspect and modify generated SQL, Python, and R code." },
    { q: "How does Vivexa prevent AI hallucinations?", a: "Every statement generated by Vivexa is verified against deterministic SQL queries, mathematical formula executions, and schema column validation before presentation." }
  ];

  return (
    <div className="relative min-h-screen bg-[#030712] text-white selection:bg-indigo-500/30">
      <AppBackground centered={false}>
        <PublicNavbar />

        <main className="pt-28 pb-20 relative z-10 max-w-7xl mx-auto px-6 lg:px-8 space-y-12">
          {/* Header */}
          <div className="text-center max-w-3xl mx-auto space-y-4">
            <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-300 text-xs font-bold">
              <BookOpen className="h-4 w-4" /> Documentation & Knowledge Hub
            </div>
            <h1 className="text-4xl sm:text-6xl font-black tracking-tight">
              Developer <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 via-purple-400 to-cyan-400">Resources & Docs</span>
            </h1>
            <p className="text-slate-400 text-sm sm:text-base leading-relaxed">
              Explore user manuals, API endpoints, SDK references, and community guides.
            </p>
          </div>

          {/* Tabs */}
          <div className="flex flex-wrap justify-center gap-2 border-b border-slate-800 pb-4">
            {[
              { id: "docs", name: "User Documentation", icon: FileText },
              { id: "developer", name: "Developer API & SDK", icon: Code2 },
              { id: "faq", name: "FAQ & Support", icon: HelpCircle }
            ].map((t) => {
              const Icon = t.icon;
              const isActive = activeTab === t.id;
              return (
                <button
                  key={t.id}
                  onClick={() => setSearchParams({ tab: t.id })}
                  className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-xs font-bold transition-all ${
                    isActive
                      ? "bg-indigo-600 text-white shadow-lg shadow-indigo-600/30"
                      : "bg-slate-900 text-slate-400 hover:text-white border border-slate-800"
                  }`}
                >
                  <Icon className="h-4 w-4" />
                  {t.name}
                </button>
              );
            })}
          </div>

          {/* Tab Content */}
          {activeTab === "docs" && (
            <div className="grid md:grid-cols-3 gap-6">
              {[
                { title: "Getting Started Guide", desc: "Connecting your first dataset, configuring workspace team permissions, and running your first AI query." },
                { title: "AI Analyst Query Syntax", desc: "Best practices for framing natural language questions to generate accurate SQL joins and forecasts." },
                { title: "User Manual & Workflows", desc: "Step-by-step documentation for Notebooks, Automations, Plugins, and Observability." }
              ].map((card, i) => (
                <div key={i} className="p-6 bg-slate-900/50 border border-slate-800 rounded-3xl space-y-3">
                  <div className="text-lg font-bold text-white">{card.title}</div>
                  <div className="text-xs text-slate-400 leading-relaxed">{card.desc}</div>
                  <Link to="/workspace/manual" className="inline-flex items-center gap-1.5 text-xs font-bold text-indigo-400 hover:text-indigo-300 pt-2">
                    Open Guide <ArrowRight className="h-3.5 w-3.5" />
                  </Link>
                </div>
              ))}
            </div>
          )}

          {activeTab === "developer" && (
            <div className="bg-slate-900/50 border border-slate-800 rounded-3xl p-8 backdrop-blur-xl space-y-6">
              <div className="flex items-center justify-between border-b border-slate-800 pb-4">
                <div>
                  <h3 className="text-xl font-bold text-white">Vivexa Python & REST SDK</h3>
                  <p className="text-xs text-slate-400">Programmatically execute AI queries, export reports, and trigger automations.</p>
                </div>
                <div className="px-3 py-1 bg-indigo-500/10 border border-indigo-500/20 text-indigo-300 rounded-lg text-xs font-mono font-bold">
                  pip install vivexa-sdk
                </div>
              </div>

              <div className="p-5 bg-slate-950 rounded-2xl border border-slate-800 font-mono text-xs text-slate-300 space-y-2">
                <div className="text-indigo-400"># Example Python SDK Snippet</div>
                <div>from vivexa import Client</div>
                <br />
                <div>client = Client(api_key="vx_live_998273645")</div>
                <div>response = client.query(</div>
                <div className="pl-4">dataset_id="ds_revenue_2026",</div>
                <div className="pl-4">prompt="Forecast Q3 revenue growth by region"</div>
                <div>)</div>
                <div>print(response.sql, response.forecast_summary)</div>
              </div>
            </div>
          )}

          {activeTab === "faq" && (
            <div className="space-y-4 max-w-3xl mx-auto">
              {faqs.map((f, i) => (
                <div key={i} className="p-6 bg-slate-900/50 border border-slate-800 rounded-2xl space-y-2">
                  <div className="text-base font-bold text-white flex items-center gap-2">
                    <HelpCircle className="h-5 w-5 text-indigo-400 shrink-0" />
                    {f.q}
                  </div>
                  <div className="text-xs text-slate-300 leading-relaxed pl-7">{f.a}</div>
                </div>
              ))}
            </div>
          )}
        </main>

        <PublicFooter />
      </AppBackground>
    </div>
  );
}
